Repository LearnWeb3DAO/Sophomore-Track, pull requests merged in 2022-11, with the labels that each got.

#35 line-break typo
  Providers-Signers-ABIs-and-Approvals.md
Labels: documentation

#8 Update What-is-Gas.md and What-is-Mining.md Regarding the ETH 2.0 or Eth2 misnomer and Post Merge edits.
  What-is-Gas.md
  What-is-Mining.md
Labels: documentation, question

#37 fix line-break bug
  Providers-Signers-ABIs-and-Approvals.md
Labels: documentation, question

#38 Few updates
  Whitelist-dApp.md
Labels: documentation, question

#33 enable owner to withdraw via frontend & participate in mint
  Initial-Coin-Offering.md
Labels: addition, question
