Repository LearnWeb3DAO/Sophomore-Track, pull requests merged in 2022-12, with the labels that each got.

#39 fixing up language and grammar issues in Proof of Stake
  Proof-of-Stake.md
Labels: documentation, good first issue, question

#34 enable DAO owner to withdraw DAO ether via frontend
  Decentralized-Autonomous-Organizations.md
Labels: addition, question

#40 fixed typo
  NFT-Collection.md
Labels: documentation, good first issue

#41 Fix
  Initial-Coin-Offering.md
  NFT-Collection.md
Labels: documentation
