Repository LearnWeb3DAO/Sophomore-Track, pull requests merged in 2023-03, with the labels that each got.

#68 fixed the typo errors
  NFT-Collection.md
Labels: documentation

#69 fixed the typo errors
  DeFi-Exchange-Theory.md
Labels: documentation

#73 PoS Resource - a blog by Vitalik
  Proof-of-Stake.md
Labels: documentation

#72 Comments for enum value
  Advanced-Solidity.md
Labels: documentation, question

#76 using the recommended method of sending ether
  Decentralized-Autonomous-Organizations.md
Labels: documentation

#77 fixed typo
  DeFi-Exchange-Theory.md
Labels: documentation

#75 update the equation
  DeFi-Exchange-Theory.md
Labels: bug, documentation, admin
