Repository LearnWeb3DAO/Sophomore-Track, pull requests merged in 2023-01, with the labels that each got.

#43 corrected the spelling
  Proof-of-Stake.md
Labels: documentation, good first issue

#56 Update LW3Tokens/ETH swap example
  DeFi-Exchange-Theory.md
Labels: documentation

#57 Adding in the Starter Template
  Decentralized-Autonomous-Organizations.md
Labels: documentation, addition, admin, test
