Repository LearnWeb3DAO/Sophomore-Track, pull requests merged in 2023-02, with the labels that each got.

#59 Fixed few issues
  Decentralized-Autonomous-Organizations.md
Labels: documentation, addition

#62 Changed Default Network to Goerli
  Decentralized-Autonomous-Organizations.md
Labels: documentation

#61 Update Initial-Coin-Offering.md
  Initial-Coin-Offering.md
Labels: documentation, good first issue

#60 Specified `ethers` version to 5.x.x
  Initial-Coin-Offering.md
  NFT-Collection.md
  Whitelist-dApp.md
Labels: bug, documentation, good first issue

#66 fixed the typo errors
  What-is-Gas.md
Labels: documentation

#67 fixed the typo in the image
  Ethereum-Virtual-Machine.md
Labels: documentation, good first issue
